shell /usr/bin/zsh

# =========================================================
# KITTY — DEV SETUP
# =========================================================

# -------------------------
# SHELL
# -------------------------

shell /usr/bin/zsh


# -------------------------
# FONTE
# -------------------------

font_family      0xProto Nerd Font Mono
font_size        11

# Se tiver uma Nerd Font instalada, pode usar:
# font_family JetBrainsMono Nerd Font


# -------------------------
# CURSOR
# -------------------------
cursor_shape block
cursor_blink_interval 0.5
cursor_stop_blinking_after 0

cursor #ECEFF4
cursor_text_color #1E222A



# -------------------------
# JANELA
# -------------------------

remember_window_size yes
initial_window_width  1200
initial_window_height 700

window_padding_width 10

hide_window_decorations yes

background_opacity 0.8

dynamic_background_opacity yes


# -------------------------
# CORES
# -------------------------

foreground              #D8DEE9
background              #1E222A

selection_foreground    #1E222A
selection_background    #88C0D0

url_color               #81A1C1


# -------------------------
# CORES ANSI
# -------------------------

color0  #3B4252
color1  #BF616A
color2  #A3BE8C
color3  #EBCB8B
color4  #81A1C1
color5  #B48EAD
color6  #88C0D0
color7  #E5E9F0

color8  #4C566A
color9  #BF616A
color10 #A3BE8C
color11 #EBCB8B
color12 #81A1C1
color13 #B48EAD
color14 #8FBCBB
color15 #ECEFF4


# -------------------------
# TAB BAR
# -------------------------

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

active_tab_foreground   #ECEFF4
active_tab_background   #5E81AC

inactive_tab_foreground #D8DEE9
inactive_tab_background #2E3440

tab_title_template "{index}: {title}"


# -------------------------
# SCROLLBACK
# -------------------------

scrollback_lines 10000

wheel_scroll_multiplier 5.0


# -------------------------
# MOUSE
# -------------------------

copy_on_select no

strip_trailing_spaces smart

url_style curly


# -------------------------
# ATALHOS
# -------------------------

# Nova aba
map ctrl+shift+t new_tab

# Fechar aba
map ctrl+shift+w close_tab

# Próxima aba
map ctrl+tab next_tab

# Aba anterior
map ctrl+shift+tab previous_tab

# Abrir shell em nova janela
map ctrl+shift+enter new_window

# Reload da configuração
map ctrl+shift+f5 load_config_file


# -------------------------
# SPLITS
# -------------------------

# Split vertical
map ctrl+shift+v launch --location=vsplit

# Split horizontal
map ctrl+shift+h launch --location=hsplit


# -------------------------
# COPIAR / COLAR
# -------------------------

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard


# -------------------------
# URLS
# -------------------------

open_url_with default

detect_urls yes

