general {
    hide_cursor = false
}

background {
    monitor = 
    path = screenshot
    blur_passes = 2
    contrast = 0.9
    brightness = 0.6
    vibrancy = 0.17
    vibrancy_darkness = 0
}

image {
    monitor = 
    path = ~/Pictures/arch_linux_logo.png
    size = 150
    rounding = 0

    border_size = 0

    halign = center
    valign = center
    position = 0, 0
}

input-field {
    monitor =
    size = 100, 30
    halign = center
    valign = center
    position = 0, -125

    outline_thickness = 3

    outer_color = rgb(42123D)
    inner_color = rgb(539FE8)
    font_color = rgb(42123D)
    check_color = rgb(FFFFFF)

    font_family = Jersey 10 Regular
    placeholder_text =   #[hyprlock] password for $USER:
    fail_text = Sorry, try again
}

label {
    monitor = 
    text = cmd[update:1000] echo "$TIME"
    color = rgb(1AD646)
    font_family = Jersey 10 Regular
    font_size = 80

    halign = right
    valign = bottom
    position = -200, 150

    shadow_passes = 5
    shadow_size = 10
}

label {
    monitor =
    text = cmd[] LC_TIME=pt_BR.UTF-8 date +"%d de %B, %Y"
    font_family = Jersey 10 Regular
    font_size = 25
    color = rgb(1AD646)

    halign = right
    valign = bottom
    position = -203, 130

    shadow_passes = 5
    shadow_size = 10
}

label {
    monitor = 
    text = 
    font_size = 20
    color = rgb(F1C40F)

    halign = left
    valign = bottom
    position = 250, 132

    onclick = ~/scripts/hyprsunsetToggle.sh
}

label {
    monitor = 
    text =  
    font_size = 20
    color = rgb(539FE8)

    halign = left
    valign = bottom
    position = 200, 130

    onclick = shutdown now
}
